import React, { useCallback } from 'react';
import MarketWatch from '../components/MarketWatch';
import TopKeywords from '../components/TopKeywords';
import NewsPanel from '../components/NewsPanel';
import FinancePanel from '../components/FinancePanel';
import PredictionPanel from '../components/PredictionPanel';
import SitrepPanel from '../components/SitrepPanel';
import ErrorBoundary from '../components/ErrorBoundary';
import { useData } from '../context/DataContext';
import { useUI } from '../context/UIContext';