import React from 'react';
import FilterBar from '../components/FilterBar';
import Globe from '../components/Globe';
import Map2D from '../components/Map2D';
import RegionPanel from '../components/RegionPanel';
import TensionChart from '../components/TensionChart';
import FlightConsole from '../components/FlightConsole';
import ErrorBoundary from '../components/ErrorBoundary';
import { useData } from '../context/DataContext';
import { useUI } from '../context/UIContext';