/**
 * VERIDIAN — Report Export Utility
 * Exports intelligence reports as formatted text to clipboard or download
 */

const WATERMARK = `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  VERIDIAN Intelligence Platform
  Geopolitical Intelligence · AI Trading Signals
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;

const DISCLAIMER = `\n\n────────────────────────────────────
DISCLAIMER: This report is AI-generated from publicly available OSINT data.
It is not financial advice. All signals are probabilistic assessments.
Generated by VERIDIAN Intelligence Platform.
────────────────────────────────────`;

/**
 * Export Country Intelligence Brief
 */
export function exportBrief(brief) {
  if (!brief) return '';

  const report = `${WATERMARK}

╔══════════════════════════════════════════════════╗
  COUNTRY INTELLIGENCE BRIEF
  Subject: ${brief.countryName || 'Unknown'}
  Generated: ${brief.analyzedAt || new Date().toISOString()}
╚══════════════════════════════════════════════════╝

■ STABILITY SCORE: ${brief.stabilityScore}/100
■ OUTLOOK: ${brief.outlook}
■ CONFIDENCE: ${brief.confidenceLevel}%

══════════ INTELLIGENCE ASSESSMENT ══════════

${brief.briefText || 'No assessment available.'}

══════════ TOP RISKS ══════════

${(brief.topRisks || []).map((r, i) => `  ${i + 1}. [${r.severity}] ${r.risk}`).join('\n')}

══════════ KEY ACTORS ══════════

${(brief.keyActors || []).map((a, i) => `  ${i + 1}. ${a}`).join('\n')}

══════════ ESCALATION FACTORS ══════════

${(brief.escalationFactors || []).map((f, i) => `  ▲ ${f}`).join('\n')}

══════════ DE-ESCALATION FACTORS ══════════

${(brief.deescalationFactors || []).map((f, i) => `  ▼ ${f}`).join('\n')}

══════════ ECONOMIC IMPACT ══════════

${brief.economicImpact || 'N/A'}

══════════ MILITARY POSTURE ══════════

${brief.militaryPosture || 'N/A'}

══════════ DIPLOMATIC STATUS ══════════

${brief.diplomaticStatus || 'N/A'}

══════════ HUMANITARIAN CONCERNS ══════════

${brief.humanitarianConcerns || 'N/A'}

══════════ AFFECTED STOCKS ══════════

${(brief.topStocks || []).map(s => `  $${s.ticker} (${s.name})\n    → ${s.reasoning}`).join('\n\n')}

══════════ AFFECTED SECTORS ══════════

  ${(brief.affectedSectors || []).join(' · ')}

══════════ HISTORICAL PARALLEL ══════════

${brief.historicalParallel || 'N/A'}

══════════ DATA SOURCES ══════════

  Events: ${brief.liveDataSources?.eventsCount || 0} | News: ${brief.liveDataSources?.newsCount || 0}
  Flights: ${brief.liveDataSources?.flightsCount || 0} | Cyber: ${brief.liveDataSources?.cyberCount || 0}
${DISCLAIMER}`;

  return report;
}

/**
 * Export SITREP
 */
export function exportSitrep(sitrep) {
  if (!sitrep) return '';

  const report = `${WATERMARK}

╔══════════════════════════════════════════════════╗
  GLOBAL SITUATIONAL REPORT (SITREP)
  Threat Level: ${sitrep.globalThreatLevel}
  Generated: ${sitrep.analyzedAt || new Date().toISOString()}
╚══════════════════════════════════════════════════╝

══════════ EXECUTIVE SUMMARY ══════════

${sitrep.summary || 'No summary available.'}

══════════ TOP THREATS ══════════

${(sitrep.topThreats || []).map((t, i) => `  ${i + 1}. [${t.severity}] ${t.title}\n     Region: ${t.region}\n     ${t.description}`).join('\n\n')}

══════════ ESCALATION WATCH ══════════

${(sitrep.escalationWatch || []).map((e, i) => `  ${i + 1}. ${e.threat}\n     Probability: ${e.probability}% | Timeframe: ${e.timeframe}\n     Trigger: ${e.trigger}`).join('\n\n')}

══════════ MARKET IMPLICATIONS ══════════

${sitrep.marketImplications || 'N/A'}

══════════ EMERGING PATTERNS ══════════

${(sitrep.emergingPatterns || []).map((p, i) => `  ${i + 1}. ${p}`).join('\n')}

══════════ RECOMMENDATIONS ══════════

${(sitrep.recommendations || []).map((r, i) => `  ${i + 1}. ${r}`).join('\n')}

══════════ DATA SNAPSHOT ══════════

  Critical Events: ${sitrep.dataSnapshot?.criticalEvents || 0}
  High Events: ${sitrep.dataSnapshot?.highEvents || 0}
  Total Events: ${sitrep.dataSnapshot?.totalEvents || 0}
  Military Flights: ${sitrep.dataSnapshot?.militaryFlights || 0}
  Cyber Threats: ${sitrep.dataSnapshot?.cyberThreats || 0}
  Breaking News: ${sitrep.dataSnapshot?.breakingNews || 0}
${DISCLAIMER}`;

  return report;
}

/**
 * Export Trading Signal
 */
export function exportSignal(signal) {
  if (!signal) return '';

  const report = `${WATERMARK}

╔══════════════════════════════════════════════════╗
  GEOTRADE SIGNAL REPORT
  Ticker: $${signal.ticker}
  Signal: ${signal.signal} | Confidence: ${signal.confidence}%
  Generated: ${signal.analyzedAt || new Date().toISOString()}
╚══════════════════════════════════════════════════╝

■ SIGNAL: ${signal.signal}
■ CONFIDENCE: ${signal.confidence}%
■ TIME HORIZON: ${signal.timeHorizon}

══════════ ANALYSIS ══════════

${signal.reasoning || 'No analysis available.'}

══════════ GEOPOLITICAL FACTORS ══════════

${(signal.geopoliticalFactors || []).map((f, i) => `  ${i + 1}. ${f}`).join('\n')}

══════════ RISK FACTORS ══════════

${(signal.riskFactors || []).map((f, i) => `  ${i + 1}. ${f}`).join('\n')}

══════════ CORRELATED ASSETS ══════════

${(signal.correlatedAssets || []).map((a, i) => `  ${i + 1}. ${a}`).join('\n')}

══════════ STOP-LOSS TRIGGER ══════════

${signal.stopLossReasoning || 'N/A'}
${DISCLAIMER}`;

  return report;
}

/**
 * Copy report to clipboard
 */
export async function copyToClipboard(text, toast) {
  try {
    await navigator.clipboard.writeText(text);
    if (toast) toast('Report copied to clipboard', 'success');
    return true;
  } catch {
    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-9999px';
    document.body.appendChild(textArea);
    textArea.select();
    document.execCommand('copy');
    document.body.removeChild(textArea);
    if (toast) toast('Report copied to clipboard', 'success');
    return true;
  }
}

/**
 * Download report as .txt file
 */
export function downloadReport(text, filename) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `veridian-report-${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
