import React, { useState, useCallback, useEffect, useRef, createContext, useContext } from 'react';

// ─── Toast Context ───────────────────────────────────────────
// Creates a React context for toast state. Consumed via useToast()
// anywhere inside <ToastProvider>. Initialised to null so missing
// providers are caught early at runtime.
const ToastContext = createContext(null);

export function useToast() {
  // Convenience hook — components call useToast() instead of
  // importing both useContext and ToastContext separately.
  return useContext(ToastContext);
}

// ─── Toast Types & Config ────────────────────────────────────
// Central config map keyed by toast type string.
// Each entry defines the visual identity (icon, colours, timing)
// for one category of alert. Adding a new type only requires a
// new entry here — no other file needs to change.
//
// Colour palette reference:
//   CRITICAL / BREAKING  →  red     (rgba 239 68 68)
//   HIGH                 →  orange  (rgba 249 115 22)
//   SURGE                →  green   (rgba 0 255 136)  — market upside
//   SIGNAL               →  cyan    (rgba 0 212 255)  — AI-generated trade signals
//   INFO                 →  cyan    (rgba 0 212 255)  — lighter opacity variant
//
// SIGNAL specifically uses cyan to visually distinguish AI-driven
// signals from human-authored alerts (red/orange). The higher
// bgFrom opacity (0.18 vs 0.12) and border opacity (0.45 vs 0.25)
// make SIGNAL toasts slightly more prominent than generic INFO,
// reflecting their actionable nature. Duration is 12 000 ms —
// the longest of all types — giving traders time to act.
const TOAST_CONFIG = {
  CRITICAL: {
    icon: 'fa-triangle-exclamation',
    label: 'CRITICAL ALERT',
    color: 'var(--color-red)',
    bgFrom: 'rgba(239, 68, 68, 0.15)',
    bgTo: 'rgba(239, 68, 68, 0.05)',
    border: 'rgba(239, 68, 68, 0.4)',
    glow: 'rgba(239, 68, 68, 0.15)',
    duration: 8000,
  },
  HIGH: {
    icon: 'fa-bolt',
    label: 'HIGH SEVERITY',
    color: 'var(--color-orange)',
    bgFrom: 'rgba(249, 115, 22, 0.15)',
    bgTo: 'rgba(249, 115, 22, 0.05)',
    border: 'rgba(249, 115, 22, 0.3)',
    glow: 'rgba(249, 115, 22, 0.1)',
    duration: 6000,
  },
  BREAKING: {
    icon: 'fa-tower-broadcast',
    label: 'BREAKING',
    color: 'var(--color-red)',
    bgFrom: 'rgba(239, 68, 68, 0.2)',
    bgTo: 'rgba(239, 68, 68, 0.08)',
    border: 'rgba(239, 68, 68, 0.5)',
    glow: 'rgba(239, 68, 68, 0.2)',
    duration: 10000,
  },
  SURGE: {
    icon: 'fa-chart-line',
    label: 'MARKET SURGE',
    color: 'var(--color-green)',
    bgFrom: 'rgba(0, 255, 136, 0.15)',
    bgTo: 'rgba(0, 255, 136, 0.05)',
    border: 'rgba(0, 255, 136, 0.3)',
    glow: 'rgba(0, 255, 136, 0.1)',
    duration: 6000,
  },
  // ── SIGNAL ──────────────────────────────────────────────────
  // Fired by the WebSocket `signal:autoGenerated` event handler
  // whenever the backend pushes AI-generated BUY / HOLD / SELL
  // signals derived from geopolitical or market events.
  //
  // Design intent — cyan (#00D4FF) over red/orange:
  //   • Red/orange → human-authored urgency (danger, breaking news)
  //   • Cyan       → machine intelligence, data-driven output
  // This makes SIGNAL toasts instantly recognisable at a glance
  // without competing with genuine emergency alerts.
  //
  // Opacity levels are intentionally elevated vs INFO:
  //   bgFrom 0.18 (INFO: 0.12) — slightly brighter fill
  //   border 0.45 (INFO: 0.25) — stronger edge definition
  //
  // Duration 12 000 ms is the longest in the system because a
  // trader may need to read ticker, confidence %, and source event
  // before deciding whether to act.
  SIGNAL: {
    icon: 'fa-brain',
    label: 'AI SIGNAL',
    color: 'var(--color-cyan)',
    bgFrom: 'rgba(0, 212, 255, 0.18)',
    bgTo: 'rgba(0, 212, 255, 0.06)',
    border: 'rgba(0, 212, 255, 0.45)',
    glow: 'rgba(0, 212, 255, 0.15)',
    duration: 12000,
  },
  INFO: {
    icon: 'fa-satellite-dish',
    label: 'INTEL UPDATE',
    color: 'var(--color-cyan)',
    bgFrom: 'rgba(0, 212, 255, 0.12)',
    bgTo: 'rgba(0, 212, 255, 0.04)',
    border: 'rgba(0, 212, 255, 0.25)',
    glow: 'rgba(0, 212, 255, 0.08)',
    duration: 5000,
  },
};

// Maximum number of toasts visible at one time.
// Older toasts are dropped from the tail when this limit is hit.
const MAX_TOASTS = 5;

// ─── Single Toast Component ─────────────────────────────────
// Renders one toast card. Manages its own exit animation and
// auto-dismiss timer. Hover pauses the timer (resets to 3 s on
// mouse-leave) so users can read long signal descriptions.
function Toast({ id, type, title, subtitle, onDismiss, index }) {
  // Falls back to INFO config for any unrecognised type string.
  const config = TOAST_CONFIG[type] || TOAST_CONFIG.INFO;
  const [exiting, setExiting] = useState(false);
  const timerRef = useRef(null);

  // Triggers the slide-out animation then removes the toast from
  // state after the 300 ms CSS transition completes.
  const handleDismiss = useCallback(() => {
    setExiting(true);
    setTimeout(() => onDismiss(id), 300);
  }, [id, onDismiss]);

  // Schedule auto-dismiss on mount; cancel on unmount to prevent
  // setState calls on an already-removed component.
  useEffect(() => {
    timerRef.current = setTimeout(handleDismiss, config.duration);
    return () => clearTimeout(timerRef.current);
  }, [config.duration, handleDismiss]);

  // Pause timer on hover
  const handleMouseEnter = () => clearTimeout(timerRef.current);
  const handleMouseLeave = () => {
    // Restart with a shortened 3 s window after the user moves away,
    // rather than the full original duration, to avoid toasts
    // stacking up if the user briefly hovered over many of them.
    timerRef.current = setTimeout(handleDismiss, 3000);
  };

  return (
    <div
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      className="pointer-events-auto"
      style={{
        // Stacking effect: each subsequent toast is slightly smaller
        // and more transparent, giving a layered deck appearance.
        animation: exiting
          ? 'toastSlideOut 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards'
          : 'toastSlideIn 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        marginBottom: 8,
        transform: `translateX(0) scale(${1 - index * 0.02})`,
        opacity: 1 - index * 0.1,
        zIndex: 100 - index,
      }}
    >
      <div
        className="relative overflow-hidden rounded-sm backdrop-blur-xl"
        style={{
          // Per-type gradient pulled from TOAST_CONFIG gives each
          // category a distinct coloured glass appearance.
          background: `linear-gradient(135deg, ${config.bgFrom}, ${config.bgTo})`,
          border: `1px solid ${config.border}`,
          boxShadow: `0 4px 20px ${config.glow}, 0 0 1px ${config.border}`,
          minWidth: 340,
          maxWidth: 420,
        }}
      >
        {/* Progress bar — shrinks from 100 % → 0 % over config.duration ms,
            giving the user a visual countdown before auto-dismiss. */}
        <div
          className="absolute top-0 left-0 h-[2px]"
          style={{
            background: config.color,
            animation: `toastProgress ${config.duration}ms linear forwards`,
            boxShadow: `0 0 6px ${config.color}`,
          }}
        />

        <div className="flex items-start gap-3 p-3.5">
          {/* Icon badge — small coloured square with the type's FA icon */}
          <div
            className="flex-shrink-0 w-8 h-8 rounded-sm flex items-center justify-center mt-0.5"
            style={{
              background: `${config.color}15`,
              border: `1px solid ${config.color}30`,
            }}
          >
            <i
              className={`fa-solid ${config.icon}`}
              style={{ color: config.color, fontSize: 12 }}
            />
          </div>

          {/* Content */}
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              {/* Type label pill — e.g. "AI SIGNAL", "CRITICAL ALERT" */}
              <span
                className="text-[7px] font-bold uppercase tracking-[0.25em] px-1.5 py-0.5 rounded-sm"
                style={{
                  color: config.color,
                  background: `${config.color}15`,
                  border: `1px solid ${config.color}25`,
                }}
              >
                {config.label}
              </span>
              {/* Timestamp — rendered at paint time, not updated live */}
              <span className="text-[8px] font-mono text-white/20">
                {new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}
              </span>
            </div>
            {/* Primary message — e.g. "BUY AAPL — 87% Confidence" */}
            <p className="text-white text-[11px] font-bold leading-tight line-clamp-2 tracking-tight">
              {title}
            </p>
            {/* Secondary line — e.g. "AUTO-SIGNAL • TAIWAN STRAIT TENSION..." */}
            {subtitle && (
              <p className="text-white/40 text-[9px] mt-1 font-mono uppercase tracking-wider">
                {subtitle}
              </p>
            )}
          </div>

          {/* Close button — dismisses immediately without waiting for timer */}
          <button
            onClick={handleDismiss}
            className="flex-shrink-0 text-white/20 hover:text-white/60 transition-colors bg-transparent border-none cursor-pointer p-1"
          >
            <i className="fa-solid fa-xmark text-[10px]" />
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Toast Provider ──────────────────────────────────────────
// Wraps the app (or a subtree) and exposes { addToast, dismissToast }
// via ToastContext. The fixed overlay container lives here so it
// is rendered exactly once regardless of how many components call
// useToast() simultaneously.
export function ToastProvider({ children }) {
  const [toasts, setToasts] = useState([]);
  const toastIdRef = useRef(0);

  // addToast({ type, title, subtitle }) → id
  // Prepends the new toast so the latest appears at the top,
  // then trims the array to MAX_TOASTS to prevent overflow.
  const addToast = useCallback(({ type = 'INFO', title, subtitle }) => {
    const id = ++toastIdRef.current;
    setToasts(prev => {
      const next = [{ id, type, title, subtitle }, ...prev];
      return next.slice(0, MAX_TOASTS);
    });
    return id;
  }, []);

  // dismissToast(id) — called by the Toast component after its
  // slide-out animation finishes, or immediately on close-click.
  const dismissToast = useCallback((id) => {
    setToasts(prev => prev.filter(t => t.id !== id));
  }, []);

  return (
    <ToastContext.Provider value={{ addToast, dismissToast }}>
      {children}
      {/* Toast Container - fixed bottom right */}
      {/* top-[220px] clears the main nav + sub-nav bars.
          pointer-events-none on the wrapper lets clicks pass through
          the empty space; pointer-events-auto is restored on each
          individual Toast so interactions still work. */}
      <div
        className="fixed top-[220px] right-4 z-[9998] flex flex-col pointer-events-none"
        style={{ maxHeight: '80vh' }}
      >
        {toasts.map((toast, index) => (
          <Toast
            key={toast.id}
            {...toast}
            index={index}
            onDismiss={dismissToast}
          />
        ))}
      </div>
    </ToastContext.Provider>
  );
}